version: "3.9"
services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - 5432:5432
  api:
    container_name: api
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./src:/app
    links:
      - database
    environment:
      - db_drive=postgresql+pg8000
      - db_user=postgres
      - db_password=example
      - POSTGRES_SERVICE_HOST=database
      - POSTGRES_SERVICE_PORT=5432
      - db_name=example
    depends_on:
      - database