"""unique constraints

Revision ID: d54d6e98d320
Revises: 5b5c9e880ba5
Create Date: 2022-02-23 20:20:30.804555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54d6e98d320'
down_revision = '5b5c9e880ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'claims', ['description'])
    op.create_unique_constraint(None, 'claims', ['id'])
    op.create_unique_constraint(None, 'roles', ['description'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'claims', type_='unique')
    op.drop_constraint(None, 'claims', type_='unique')
    # ### end Alembic commands ###
